min_length: 5
max_length: 10

texts:
  vocabs:
    - resources/vocabs/vi.txt
    - resources/vocabs/digits.txt
    - resources/vocabs/specials.txt
  dictionaries:
    - resources/dicts/websites.txt

text_colors:
  colors:
    - "#ffffff"
    - "#000000"
  palettes:
    - "#000000:#ffffff"

fonts: resources/fonts/vietnamese/

backgrounds:
  colors:
    - from: [0, 0, 0]
      to: [50, 50, 50]
    - from: [200, 200, 200]
      to: [255, 255, 255]
  images:
    - resources/backgrounds
