output: outputs/vi-bootstrap
count: r

texts:
  - name: VocabRep
    vocab_file: resources/vocabs/vi.txt
    max_length: 50
  - name: VocabRep
    vocab_file: resources/vocabs/latin.txt
    max_length: 50
  - name: VocabRep
    vocab_file: resources/vocabs/specials.txt
    max_length: 50
  - name: VocabRep
    vocab_file: resources/vocabs/digits.txt
    max_length: 50

fonts:
  - name: FontDir
    path: resources/fonts/vietnamese/

foregrounds:
  - name: Color
    a: [0, 0, 0]
    b: [255, 255, 255]
    image: false
    count: 500

backgrounds:
  - name: Color
    a: [0, 0, 0]
    b: [50, 50, 50]
    count: 20
  - name: Color
    a: [200, 200, 200]
    b: [255, 255, 255]
    count: 20
  - name: ImageDir
    path: resources/backgrounds/
